### ISSUE TITLE
Cannot filter persons using an array of organizations as filter

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc#36]
The schema of the filter:

```
type: object
description: An object that describes how to filter Persons
properties:
  firstName:
    description: Keep the persons whose first name starts with this term
    type: string
  lastName:
    description: Keep the persons whose last name starts with this term
    type: string
  email:
    description: Keep the persons whose email matches this term
    type: string
  organizations:
    description: Keep the persons who belong to these organizations
    type: array
    items:
      $ref: OrganizationId.yaml
```

The example filter generated by the documentation UI of the server:

```
{
  "email": "string",
  "firstName": "string",
  "lastName": "string",
  "organizations": [
    "awesome-organization"
  ]
}
```

The error returned by the server when using this filter:

```
{
  "detail": "'awesome-organization' is not of type 'array'\n\nFailed validating 'type' in schema['properties']['organizations']:\n    {'description': 'Keep the persons who belong to these organizations',\n     'items': {'description': 'The ID of the organization',\n               'example': 'awesome-organization',\n               'maxLength': 60,\n               'minLength': 3,\n               'pattern': '^[a-z0-9]+(?:-[a-z0-9]+)*$',\n               'type': 'string',\n               'x-scope': ['', '#/components/schemas/PersonFilter']},\n     'type': 'array'}\n\nOn instance['organizations']:\n    'awesome-organization'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```
