### ISSUE TITLE
Update query parameter values for sorting challenges

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc#40]
## Task

- [ ] Update schema to support the sorting strategies that we have identified
- [ ] Document in the schema what each sorting strategy value means (can we add a `description` to `enum` values?)

![image](https://user-images.githubusercontent.com/3056480/143068891-c82d143c-4012-4cde-b1dc-3f29dc063dbb.png)

Reference: [Lucidchart](https://www.figma.com/file/jnysPrzhIZOlhYlTY3CAWN/search%2Fchallenges?node-id=0%3A1)

**Comment by rrchai** [comment]
> Document in the schema what each sorting strategy value means (can we add a description to enum values?)

@tschaffter Would it possible to tell me more about this task when you have time? Can you give me an example like, where should I add documents in the schema?

**Comment by tschaffter** [comment]
Here is an example of description given for an enum parameter.

```
          parameters:
            - in: query
              name: sort
              schema:
                type: string
                enum: [asc, desc]
              description: >
                Sort order:
                 * `asc` - Ascending, from A to Z
                 * `desc` - Descending, from Z to A
```

[Source](https://swagger.io/docs/specification/data-models/enums/)
